# 
# WARNING: Generated Configuration using - docker/gradient.yml
# 
name: gradient-parser
services:
  generate:
    command:
      - python
      - /app/generate_new_gradient.py
    environment:
      - BASE_ONE
      - BASE_TWO
    image: dev.caracolazul.python-colormath
    networks:
      default: null
    volumes:
      - type: bind
        source: .
        target: /app
        bind:
          create_host_path: true
  report:
    build:
      context: ./docker/colormath
      dockerfile: Dockerfile
    image: dev.caracolazul.python-colormath
    networks:
      default: null
    volumes:
      - type: bind
        source: .
        target: /app
        bind:
          create_host_path: true
networks:
  default:
    name: gradient-parser_default
