name: gradient-parser
services:
  generate:
    command:
      - python
      - /app/generate_new_gradient.py
    environment:
      BASE_ONE: '#000462'
      BASE_TWO: '#DCEBFE'
    image: dev.caracolazul.python-colormath
    networks:
      default: null
    volumes:
      - type: bind
        source: /home/mzd/Lab/gradient-parser
        target: /app
        bind:
          create_host_path: true
  report:
    build:
      context: /home/mzd/Lab/gradient-parser/docker/colormath
      dockerfile: Dockerfile
    image: dev.caracolazul.python-colormath
    networks:
      default: null
    volumes:
      - type: bind
        source: /home/mzd/Lab/gradient-parser
        target: /app
        bind:
          create_host_path: true
networks:
  default:
    name: gradient-parser_default
